// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: open_ai/open_ai.proto

package v1

import (
	reflect "reflect"
	sync "sync"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetChatCompletionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetChatCompletionsRequest) Reset() {
	*x = GetChatCompletionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_open_ai_open_ai_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChatCompletionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatCompletionsRequest) ProtoMessage() {}

func (x *GetChatCompletionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_open_ai_open_ai_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatCompletionsRequest.ProtoReflect.Descriptor instead.
func (*GetChatCompletionsRequest) Descriptor() ([]byte, []int) {
	return file_open_ai_open_ai_proto_rawDescGZIP(), []int{0}
}

func (x *GetChatCompletionsRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetChatCompletionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetChatCompletionsResponse) Reset() {
	*x = GetChatCompletionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_open_ai_open_ai_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChatCompletionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatCompletionsResponse) ProtoMessage() {}

func (x *GetChatCompletionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_open_ai_open_ai_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatCompletionsResponse.ProtoReflect.Descriptor instead.
func (*GetChatCompletionsResponse) Descriptor() ([]byte, []int) {
	return file_open_ai_open_ai_proto_rawDescGZIP(), []int{1}
}

func (x *GetChatCompletionsResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetChatCompletionsStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetChatCompletionsStreamRequest) Reset() {
	*x = GetChatCompletionsStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_open_ai_open_ai_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChatCompletionsStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatCompletionsStreamRequest) ProtoMessage() {}

func (x *GetChatCompletionsStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_open_ai_open_ai_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatCompletionsStreamRequest.ProtoReflect.Descriptor instead.
func (*GetChatCompletionsStreamRequest) Descriptor() ([]byte, []int) {
	return file_open_ai_open_ai_proto_rawDescGZIP(), []int{2}
}

func (x *GetChatCompletionsStreamRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetChatCompletionsStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetChatCompletionsStreamResponse) Reset() {
	*x = GetChatCompletionsStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_open_ai_open_ai_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChatCompletionsStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatCompletionsStreamResponse) ProtoMessage() {}

func (x *GetChatCompletionsStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_open_ai_open_ai_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatCompletionsStreamResponse.ProtoReflect.Descriptor instead.
func (*GetChatCompletionsStreamResponse) Descriptor() ([]byte, []int) {
	return file_open_ai_open_ai_proto_rawDescGZIP(), []int{3}
}

func (x *GetChatCompletionsStreamResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_open_ai_open_ai_proto protoreflect.FileDescriptor

var file_open_ai_open_ai_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x61, 0x69, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x61,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x69, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x43,
	0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x32, 0x0a, 0x1a, 0x47,
	0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x37, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x38, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x43,
	0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x32, 0xab, 0x02, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x49, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x91, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2c, 0x2e, 0x6f, 0x70,
	0x65, 0x6e, 0x61, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x6f, 0x70, 0x65, 0x6e,
	0x61, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18,
	0x3a, 0x01, 0x2a, 0x22, 0x13, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x85, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x32, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x69, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61,
	0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x6f, 0x70, 0x65, 0x6e,
	0x61, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x0c, 0x5a, 0x0a, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x61, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_open_ai_open_ai_proto_rawDescOnce sync.Once
	file_open_ai_open_ai_proto_rawDescData = file_open_ai_open_ai_proto_rawDesc
)

func file_open_ai_open_ai_proto_rawDescGZIP() []byte {
	file_open_ai_open_ai_proto_rawDescOnce.Do(func() {
		file_open_ai_open_ai_proto_rawDescData = protoimpl.X.CompressGZIP(file_open_ai_open_ai_proto_rawDescData)
	})
	return file_open_ai_open_ai_proto_rawDescData
}

var file_open_ai_open_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_open_ai_open_ai_proto_goTypes = []interface{}{
	(*GetChatCompletionsRequest)(nil),        // 0: openai.service.v1.GetChatCompletionsRequest
	(*GetChatCompletionsResponse)(nil),       // 1: openai.service.v1.GetChatCompletionsResponse
	(*GetChatCompletionsStreamRequest)(nil),  // 2: openai.service.v1.GetChatCompletionsStreamRequest
	(*GetChatCompletionsStreamResponse)(nil), // 3: openai.service.v1.GetChatCompletionsStreamResponse
}
var file_open_ai_open_ai_proto_depIdxs = []int32{
	0, // 0: openai.service.v1.OpenAIService.GetChatCompletions:input_type -> openai.service.v1.GetChatCompletionsRequest
	2, // 1: openai.service.v1.OpenAIService.GetChatCompletionsStream:input_type -> openai.service.v1.GetChatCompletionsStreamRequest
	1, // 2: openai.service.v1.OpenAIService.GetChatCompletions:output_type -> openai.service.v1.GetChatCompletionsResponse
	3, // 3: openai.service.v1.OpenAIService.GetChatCompletionsStream:output_type -> openai.service.v1.GetChatCompletionsStreamResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_open_ai_open_ai_proto_init() }
func file_open_ai_open_ai_proto_init() {
	if File_open_ai_open_ai_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_open_ai_open_ai_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChatCompletionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_open_ai_open_ai_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChatCompletionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_open_ai_open_ai_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChatCompletionsStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_open_ai_open_ai_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChatCompletionsStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_open_ai_open_ai_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_open_ai_open_ai_proto_goTypes,
		DependencyIndexes: file_open_ai_open_ai_proto_depIdxs,
		MessageInfos:      file_open_ai_open_ai_proto_msgTypes,
	}.Build()
	File_open_ai_open_ai_proto = out.File
	file_open_ai_open_ai_proto_rawDesc = nil
	file_open_ai_open_ai_proto_goTypes = nil
	file_open_ai_open_ai_proto_depIdxs = nil
}
