// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: open_ai/open_ai.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	OpenAIService_GetChatCompletions_FullMethodName       = "/openai.service.v1.OpenAIService/GetChatCompletions"
	OpenAIService_GetChatCompletionsStream_FullMethodName = "/openai.service.v1.OpenAIService/GetChatCompletionsStream"
)

// OpenAIServiceClient is the client API for OpenAIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpenAIServiceClient interface {
	GetChatCompletions(ctx context.Context, in *GetChatCompletionsRequest, opts ...grpc.CallOption) (*GetChatCompletionsResponse, error)
	GetChatCompletionsStream(ctx context.Context, in *GetChatCompletionsStreamRequest, opts ...grpc.CallOption) (*GetChatCompletionsStreamResponse, error)
}

type openAIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOpenAIServiceClient(cc grpc.ClientConnInterface) OpenAIServiceClient {
	return &openAIServiceClient{cc}
}

func (c *openAIServiceClient) GetChatCompletions(ctx context.Context, in *GetChatCompletionsRequest, opts ...grpc.CallOption) (*GetChatCompletionsResponse, error) {
	out := new(GetChatCompletionsResponse)
	err := c.cc.Invoke(ctx, OpenAIService_GetChatCompletions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openAIServiceClient) GetChatCompletionsStream(ctx context.Context, in *GetChatCompletionsStreamRequest, opts ...grpc.CallOption) (*GetChatCompletionsStreamResponse, error) {
	out := new(GetChatCompletionsStreamResponse)
	err := c.cc.Invoke(ctx, OpenAIService_GetChatCompletionsStream_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpenAIServiceServer is the server API for OpenAIService service.
// All implementations should embed UnimplementedOpenAIServiceServer
// for forward compatibility
type OpenAIServiceServer interface {
	GetChatCompletions(context.Context, *GetChatCompletionsRequest) (*GetChatCompletionsResponse, error)
	GetChatCompletionsStream(context.Context, *GetChatCompletionsStreamRequest) (*GetChatCompletionsStreamResponse, error)
}

// UnimplementedOpenAIServiceServer should be embedded to have forward compatible implementations.
type UnimplementedOpenAIServiceServer struct {
}

func (UnimplementedOpenAIServiceServer) GetChatCompletions(context.Context, *GetChatCompletionsRequest) (*GetChatCompletionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatCompletions not implemented")
}
func (UnimplementedOpenAIServiceServer) GetChatCompletionsStream(context.Context, *GetChatCompletionsStreamRequest) (*GetChatCompletionsStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatCompletionsStream not implemented")
}

// UnsafeOpenAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpenAIServiceServer will
// result in compilation errors.
type UnsafeOpenAIServiceServer interface {
	mustEmbedUnimplementedOpenAIServiceServer()
}

func RegisterOpenAIServiceServer(s grpc.ServiceRegistrar, srv OpenAIServiceServer) {
	s.RegisterService(&OpenAIService_ServiceDesc, srv)
}

func _OpenAIService_GetChatCompletions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatCompletionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenAIServiceServer).GetChatCompletions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenAIService_GetChatCompletions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenAIServiceServer).GetChatCompletions(ctx, req.(*GetChatCompletionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenAIService_GetChatCompletionsStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatCompletionsStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenAIServiceServer).GetChatCompletionsStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenAIService_GetChatCompletionsStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenAIServiceServer).GetChatCompletionsStream(ctx, req.(*GetChatCompletionsStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OpenAIService_ServiceDesc is the grpc.ServiceDesc for OpenAIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpenAIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openai.service.v1.OpenAIService",
	HandlerType: (*OpenAIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChatCompletions",
			Handler:    _OpenAIService_GetChatCompletions_Handler,
		},
		{
			MethodName: "GetChatCompletionsStream",
			Handler:    _OpenAIService_GetChatCompletionsStream_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "open_ai/open_ai.proto",
}
